### ISSUE TITLE
Make 'xesam-album' not a requirement

### ISSUE THREAD

**Issue by BladeWS** [minneyar/clementine-discord#2]
Hi and thank you for this great script.

When trying to run a internet radio stream that doesn't necessarily contains "album" info, the script crashes with:

```
INFO:__main__:Initializing.
INFO:__main__:Connecting to Clementine.
INFO:__main__:Connecting to Discord.
INFO:__main__:Shutting down.
Traceback (most recent call last):
  File "./clementine_discord.py", line 119, in <module>
    updater.run()
  File "./clementine_discord.py", line 65, in run
    self.update_loop()
  File "./clementine_discord.py", line 97, in update_loop
    details = DETAILS_STRING.format(**tmp_metadata)
KeyError: 'xesam-album'
```
I tried removing 'xesam-album' from DETAILS_STRING but then I get 

```
INFO:__main__:Initializing.
INFO:__main__:Connecting to Clementine.
INFO:__main__:Connecting to Discord.
INFO:__main__:Shutting down.
Traceback (most recent call last):
  File "./clementine_discord.py", line 119, in <module>
    updater.run()
  File "./clementine_discord.py", line 65, in run
    self.update_loop()
  File "./clementine_discord.py", line 100, in update_loop
    length_s = metadata['mpris:length'] / 1000000
KeyError: 'mpris:length'
```
Is there any way to add an exception if "xesam-album" is not found? (or/and "mpris:length")

Thank you.

**Comment by pjreed** [comment]
Thanks for the report, I just pushed up a fix that I think will catch those errors so the script will continue running, although you'll still want to manually modify `DETAILS_STRING` to display metadata that is appropriate for your internet radio stream.  Do you have any suggestions on what would be more appropriate?  I can probably modify it so that it can try multiple different strings if one doesn't work.

**Comment by minneyar** [comment]
Thanks for the report, I just pushed up a fix that I think will catch those errors so the script will continue running, although you'll still want to manually modify DETAILS_STRING to display metadata that is appropriate for your internet radio stream. Do you have any suggestions on what would be more appropriate? I can probably modify it so that it can try multiple different strings if one doesn't work.

**Comment by BladeWS** [comment]
That fixed it ! Thank you.
Now that specific radio stream can be displayed if you remove the 'xesam-album'. 

Yes, your suggestion is good. The default of the script should be always show 'xesam-title'
Then if 'xesam-album' exists, display it. If not move to "xesam:artist", maybe :)
